# Generated by Django 5.2.8 on 2025-12-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
    ]
