# Generated by Django 5.2.8 on 2026-02-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
